// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200507114007");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.discoverystream.isCollectionDismissible", true);
user_pref("app.normandy.startupRolloutPrefs.signon.management.page.os-auth.enabled", false);
user_pref("app.normandy.user_id", "27abd5e4-97ad-46c5-9c66-077a5342e883");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1593534351);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1593534806);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1593514273);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1593535212);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1593513790);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1593534167);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1593513701);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1593534736);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2428);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1593513639);
user_pref("browser.laterrun.bookkeeping.sessionCount", 10);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c1758abe-5858-4c62-a571-fd9acccdc93e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1593534151199");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1593535950199");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1593534151623");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1593537751623");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200507114007");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1593535211");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20200507114007");
user_pref("browser.startup.homepage_override.mstone", "76.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1593535198);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1593514273619");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "76.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "873d47bc2cf44b5aad7fa2fa35553f05");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1593534362);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200507114007");
user_pref("extensions.lastAppVersion", "76.0.1");
user_pref("extensions.lastPlatformVersion", "76.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"c658b054-01d3-4e0b-96eb-47d412ff391d\",\"formautofill@mozilla.org\":\"1cd74171-11bb-482b-9548-91c17d5cde1b\",\"screenshots@mozilla.org\":\"c9a7a106-4045-4cb0-946f-a1f95c7cde21\",\"webcompat-reporter@mozilla.org\":\"a50dfe11-8598-47e6-997a-2e24fa820397\",\"webcompat@mozilla.org\":\"f940813b-4008-43f3-8792-525a9eb8c0a8\",\"default-theme@mozilla.org\":\"332e349c-e8a0-4d11-a011-74b6d3f43af6\",\"google@search.mozilla.org\":\"82651224-8eae-44de-9c49-88f4b7dcc494\",\"amazondotcom@search.mozilla.org\":\"d44813f9-5e0d-43f0-86f8-cb5d9652e420\",\"bing@search.mozilla.org\":\"a8a6345a-3eb7-4d22-9a70-1711c24cd0d3\",\"ddg@search.mozilla.org\":\"64344187-735a-43bc-bbf4-736c56e96e45\",\"ebay@search.mozilla.org\":\"ae2c17d4-896c-4557-8bd1-8978c8eeae33\",\"twitter@search.mozilla.org\":\"a776c0bd-87c5-4c85-8e13-86a19ab545b5\",\"wikipedia@search.mozilla.org\":\"d9c99521-2737-44bf-913a-8c248de86e07\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20200507114007");
user_pref("media.gmp-manager.lastCheck", 1593535158);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1593535157);
user_pref("security.remote_settings.intermediates.checked", 1593535157);
user_pref("security.sandbox.content.tempDirSuffix", "f8015ea3-6f13-4af0-a882-d7b13ac63e8b");
user_pref("security.sandbox.plugin.tempDirSuffix", "1465d35b-0ab6-481a-ae9f-93f4a29ee4ca");
user_pref("services.blocklist.addons.checked", 1593535157);
user_pref("services.blocklist.gfx.checked", 1593534167);
user_pref("services.blocklist.plugins.checked", 1593535157);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1593530372996\"");
user_pref("services.settings.last_update_seconds", 1593535157);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1593534167);
user_pref("services.settings.main.cfr-fxa.last_check", 1593535157);
user_pref("services.settings.main.cfr.last_check", 1593535157);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1593535157);
user_pref("services.settings.main.hijack-blocklists.last_check", 1593535157);
user_pref("services.settings.main.language-dictionaries.last_check", 1593534167);
user_pref("services.settings.main.message-groups.last_check", 1593535157);
user_pref("services.settings.main.messaging-experiments.last_check", 1593535157);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1593535157);
user_pref("services.settings.main.public-suffix-list.last_check", 1593535157);
user_pref("services.settings.main.search-config.last_check", 1593535157);
user_pref("services.settings.main.sites-classification.last_check", 1593534167);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1593535157);
user_pref("services.settings.main.whats-new-panel.last_check", 1593535157);
user_pref("services.settings.security.onecrl.checked", 1593535157);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1593535170);
user_pref("toolkit.telemetry.cachedClientID", "d4d8c934-ea30-414d-9084-9fad8f90a50a");
user_pref("toolkit.telemetry.previousBuildID", "20200507114007");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
